### ISSUE TITLE
This repo has the wrong name

### ISSUE THREAD

**Issue by andrew-appel** [SkyLabsAI/BRiCk#3]
What you have in this repo, as I understand it, is a program logic for C++ based on separation logic, along with proof automation tactics to help the user apply the program logic to the program.  And incidentally a front-end that parses C++ programs and prints the Abstract Syntax Trees out (as Coq inductive types) into a .v file.

And yet the entire repo is named "cpp2v", as if this incidental front-end component were the substance of the entire project.

You know, if the README is misleading or something, that's easy to fix later.  But if I want to tell people about the cool work that you're doing, then it will be rather disruptive if the name of the repo changes.  So if you're going to change the name of the repo, I'd suggest sooner rather than later.

**Comment by gstew5** [comment]
> And yet the entire repo is named "cpp2v", as if this incidental front-end component were the substance of the entire project.

We have a new name in the works. We'll need to update our internal tooling before we switch the repo name, but it should happen soon.

If you need the new name before that (to cite in a paper, for example), I think we could provide it.

> What you have in this repo, as I understand it, is a program logic for C++ based on separation logic, along with proof automation tactics to help the user apply the program logic to the program.

This repo contains our C++ program logic but not the automation tactics we use in day-to-day proofs (those are not open source).

**Comment by gmalecha** [comment]
Completely agree. We are in a transitional state where we are migrating to a new name. That release will clarify names, change this repository name, and the like.

**Comment by andrew-appel** [comment]
New name, and new repository link, by December 1st would be useful.

**Comment by andrew-appel** [comment]
Seems like the repo has been renamed.
